package com.example.sadeep.winternightd.toolbar;

import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import com.example.sadeep.winternightd.buttons.customizedbuttons.ToolbarButton;
import com.example.sadeep.winternightd.selection.XSelection;
import com.example.sadeep.winternightd.spans.LiveFormattingStatus;
import com.example.sadeep.winternightd.spans.SpansController;
import com.example.sadeep.winternightd.spans.SpansFactory;

import java.util.ArrayList;

/**
 * Created by Sadeep on 10/12/2016.
 */
final public class ToolbarController {

    private ToolbarController(){}//ToolbarController cannot be instantiated

    private static ArrayList<Toolbar> toolbars = new ArrayList<>();

    public static void registerToolbar(Toolbar toolbar){
        toolbars.add(toolbar);

        //removes any toolbar generated by a different activity (context) than the newly entered one to avoid memory leaks
        for (int i = 0; i < toolbars.size(); i++) {
            if(toolbar.getContext()!=toolbars.get(i).getContext()){
                unregisterToolbar(toolbars.get(i));
                i--;
            }
        }
    }

    public static void unregisterToolbar(Toolbar toolbar){
        toolbars.remove(toolbar);
    }

    public static void dispatchToolbarUpdates(int[] spanStatus) {
        for (int i = 0; i < toolbars.size(); i++) {
            toolbars.get(i).updateStatus(spanStatus);
        }
    }

    public static void refreshToolbars(){
        dispatchToolbarUpdates(LiveFormattingStatus.format);
    }
}
